version: '3.8'

services:
  pg-database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    volumes:
      - /c/Users/emir_/data-engineering-zoomcamp/week_1_basics_n_setup/2_docker_sql/ny-taxi-volume:/var/lib/postgresql/data:/var/lib/postgresql/data \
    ports:
      - "5432:5432"
    networks:
      - pg-network
    hostname: pg-database

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - /c/Users/emir_/data-engineering-zoomcamp/week_1_basics_n_setup/2_docker_sql/ny-taxi-volume:/var/lib/postgresql/data:/var/lib/postgresql/data \
    ports:
      - "8080:80"
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge
